name: Monitor Decision Brief Sources

on:
  schedule:
    - cron: "0 14 * * 1"
    - cron: "0 14 * * 3"
    - cron: "0 14 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run hash monitor
        run: node scripts/monitoring/hash-monitor.mjs

      - name: Count proposals
        id: count
        run: |
          PROPOSALS=$(cat monitoring/proposals.json | node -e "
            let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{
              const p=JSON.parse(d);
              console.log(p.length);
            })
          ")
          echo "proposal_count=$PROPOSALS" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "monitoring: update source hashes and proposals"
          title: "Monitoring: source changes detected"
          body: |
            ## Source Monitor Run

            **Proposals detected:** ${{ steps.count.outputs.proposal_count }}

            Review the changes in [`monitoring/proposals.json`](monitoring/proposals.json) and triage each entry.

            See [`scripts/monitoring/README.md`](scripts/monitoring/README.md) for triage instructions.
          branch: monitoring/source-changes
          delete-branch: true
          add-paths: |
            monitoring/state.json
            monitoring/proposals.json
